server:
  port: 8889

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/member
    username: test
    password: test

  jpa:
    hibernate:
      #5. ddl-auto? spring boot Entity ??? ???? ??? ?? ?? = 'create'? ?? ? ?? + ??? ?? none?? ???? ?
      # create/update -> none ???? ??? ?? ???? ?????? ??? ??? ? ???
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
