### SEND post request with json body- 요청 정보 + 헤더파일 정보
POST http://localhost:8123/api/v1/member/regist
Content-Type: application/json

{
  "loginId": "user01",
  "password": "passs01",
  "name" : "홍길동",
  "phone": "010-1234-5678",
  "nickname": "hong",
  "image": "www.naver.com",
  "introduction": "hi"
}




